name: Check Code Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==24.8.0 autoflake==2.3.1 isort==5.13.2
    - name: Check with autoflake
      run: |
        autoflake --check --quiet --remove-all-unused-imports --remove-unused-variables --recursive . --exclude __init__.py
    - name: Check with isort
      run: |
        isort --check-only .
    - name: Check with black
      run: |
        black --check .